---
- name: Get Onewire status
  command: "raspi-config nonint get_onewire"
  register: onewire_status
  changed_when: False

- name: Enable OneWire.
  command: "raspi-config nonint do_onewire 0"
  when: ONEWIRE and (onewire_status.stdout != '0')

- name: Disable OneWire.
  command: "raspi-config nonint do_onewire 1"
  when: not ONEWIRE and (onewire_status.stdout != '1')
