---
- name: Check that rasp_user variable are filled in.
  fail:
      msg: "rasp_user variable is not defined."
  when: not rasp_user

- name: Check that rasp_user_password variable are filled in.
  fail:
      msg: "rasp_user_password variable is not defined."
  when: not rasp_user_password

- name: Check that rasp_user_encrypted_password variable are filled in.
  fail:
      msg: "rasp_user_encrypted_password variable is not defined."
  when: not rasp_user_encrypted_password

- name: Check that ssh_key_file variable are filled in.
  fail:
      msg: "ssh_key_file variable is not defined."
  when: not ssh_key_file
