---
- hosts:
    - pi
  become: true

  vars:
    rasp_extra_packages:
      - python3

    CAMERA: true
    rasp_ssh_port : 2222
    rasp_firewall: true
    rasp_open_firewall_port:
      - 80
      - 8080

  roles:
    - ansible/roles/raspberry_pi_config


