---
- name: Get I2C status
  command: "raspi-config nonint get_i2c"
  register: i2c_status
  changed_when: False

- name: Enable I2C.
  command: "raspi-config nonint do_i2c 0"
  when: I2C and (i2c_status.stdout != '0')

- name: Disable I2C.
  command: "raspi-config nonint do_i2c 1"
  when: not I2C and (i2c_status.stdout != '1')
