---
- name: Get remote GPIO status
  command: "raspi-config nonint get_rgpio"
  register: rgpio_status
  changed_when: False

- name: Enable Remote GPIO.
  command: "raspi-config nonint do_rgpio 0"
  when: RGPIO and (rgpio_status.stdout != '0')

- name: Disable Remote GPIO.
  command: "raspi-config nonint do_rgpio 1"
  when: not RGPIO and (rgpio_status.stdout != '1')
