---
# defaults variable for ansible_raspberry_pi_config

### replace_pi_user.yml ###
rasp_user:                      # replacement username pi
rasp_user_encrypted_password:   # password encrypted
rasp_user_password:             # password

#### ssh.yml ###
rasp_ssh_port: 22
ssh_key_file:    # full path to the id_rsa.pub key

### Interfacing Options ###
SERIAL: true
CAMERA: false
VNC: false
SPI: false
I2C: false
ONEWIRE: false
RGPIO: false

### packages.yml ###
rasp_extra_packages: [] # packages to install

### ufw.yml ###
rasp_firewall: false       # by default firewall is not actived
rasp_open_firewall_port:   # Firewall port to open
  - "{{ rasp_ssh_port }}"
